# Generated by Django 5.1.3 on 2025-08-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='total',
        ),
    ]
